### ISSUE TITLE
BUG issues

### ISSUE THREAD

**Issue by coderstory** [rarnu/root-tools#32]
测试设备 小米5 miui8

1.默认情况下 终端模拟器无无法输入文字（不会拉起输入法） 除非我点击 az 这个按钮

2.组建管理么  最好把系统app 用户app分离  app实在太多了   最好加个实时搜索

3.logo貌似是cm7的开机动画？

**Comment by coderstory** [comment]
runCommand这个方法我做了修改
process没必要每次都去new一个 这个操作很耗时

static Process process;
    static DataOutputStream os = null;
    static BufferedReader brOut = null;
    static BufferedReader brErr = null;

    public static CommandResult runCommand(String[] command, boolean root, CommandCallback callback) {

        CommandResult ret = new CommandResult();
        try {
            StringBuffer output = new StringBuffer();
            StringBuffer error = new StringBuffer();
            if (root) {
                if (process==null) {
                    process = Runtime.getRuntime().exec("su");
                }
                os = new DataOutputStream(process.getOutputStream());

                os.writeBytes(command[0] + "\n");

**Comment by rarnu** [comment]
1. 已修复
2. 已增加颜色设别，且系统app会出现在用户app的下方，实时搜索已有，请点击右上角搜索按钮
3. logo本来是随便找的。。。现在已经换了新logo

**Comment by rarnu** [comment]
关于runCommand的问题，目前的实现无疑是不对的，或者说不合我意的
后续会改成用JNI去执行命令，并且拿到返回值，java层暂时先不改了吧

**Comment by coderstory** [comment]
* What went wrong:
A problem occurred evaluating root project 'RootTools2'.
> Gradle version 2.10 is required. Current version is 1.12. If using the gradle wrapper, try editing the distributionUrl in D:\12\root-tools\RootTools2\gradle\wrapper\gradle-wrapper.properties to gradle-2.10-all.zip

**Comment by coderstory** [comment]
* What went wrong:
13:41:45.665 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring root project 'RootTools2'.
13:41:45.672 [ERROR] [org.gradle.BuildExceptionReporter] > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by coderstory** [comment]
命令行下编译挺麻烦的
