### ISSUE TITLE
I set minSDK=19 in build.gradle and manifest.xml, then build failed

### ISSUE THREAD

**Issue by aaaking** [rarnu/root-tools#34]
Error:Execution failed for task ':processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [:Emulator-release:] /Users/fuwu/codebase/github/android/root-tools/RootTools2/build/intermediates/exploded-aar/Emulator-release/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.rarnu.terminal" to force usage

**Comment by rarnu** [comment]
If you really want to do so, recompile Emulator to SDK19 by change the build.gradle under Emulator project. And then copy generated Emulator-release.aar to RootTools/aar.

Really not suggest to compile it with SDK under 21.
