### ISSUE TITLE
能不能把去广告像小米净化一样，每个app单独设置？

### ISSUE THREAD

**Issue by lukemin** [rarnu/root-tools#35]
能不能把去广告像小米净化一样，每个app单独设置？

**Comment by rarnu** [comment]
后面我给个选项吧，之前听到很多呼声是希望一键完成，而不是一个个选。众口难调

**Comment by lukemin** [comment]
谢谢，如果不是单独选的话 会造成和xmiui有些功能像mihome/mi启动器里面的启用桌面网格自定义功能 冲突，使桌面反复fc，

**Comment by rarnu** [comment]
小米运动并非内置应用，因此不在考虑之列，目前仅考虑系统内置的广告，而不是所有小米出品的APP

**Comment by lukemin** [comment]
![screenshot_2016-11-24-15-12-48-469_com xiaomi mar](https://cloud.githubusercontent.com/assets/12003375/20589664/ddc1c142-b258-11e6-844d-8ef076a7cc0a.png)
应用商店广告能够去除吗？

**Comment by rarnu** [comment]
可以的，已经接到这个需求，另外，反馈广告问题最好用APP里面的反馈功能吧~

**Comment by rarnu** [comment]
APP单独设置的功能已提供，此条关闭，有其他问题请另开issue
